name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: make zip kpartx qemu-user-static unzip
          version: 1.0

      - name: Build image
        run: |
          make image
           
      - name: upload 
        uses: actions/upload-artifact@v3
        with:
          path: "pwnagotchi-raspios-lite-*.zip"


          